"use client";

import React from "react";
import { Separator } from "@/components/ui/separator";
import { Scale, AlertTriangle, CreditCard, Zap, ShieldAlert } from "lucide-react";

export default function TermsOfService() {
  const lastUpdated = "May 4, 2026";

  const legalSections = [
    {
      title: "1. Acceptance of Terms",
      icon: <Scale className="w-5 h-5 text-primary" />,
      content:
        "By accessing or using our platform, you agree to be bound by these Terms of Service. If you do not agree, you should not use the service.",
    },
    {
      title: "2. Credits and Usage",
      icon: <CreditCard className="w-5 h-5 text-secondary" />,
      content:
        "Certain features require usage credits (“tokens”). Tokens are non-transferable and may expire based on your subscription plan. Unless otherwise stated, all purchases are final.",
    },
    {
      title: "3. AI Output Disclaimer",
      icon: <Zap className="w-5 h-5 text-accent" />,
      content:
        "Outputs generated by our AI tools, including career suggestions and resume analysis, are provided for informational purposes only. We do not guarantee their accuracy, completeness, or outcomes.",
    },
    {
      title: "4. Acceptable Use",
      icon: <ShieldAlert className="w-5 h-5 text-destructive" />,
      content:
        "You agree not to misuse the platform. This includes generating harmful or illegal content, attempting to reverse-engineer our systems, or using automated methods to abuse usage limits.",
    },
  ];

  return (
    <div className="min-h-screen pt-16 bg-black text-zinc-400 font-sans selection:bg-primary/30">
      <div className="max-w-4xl mx-auto px-6 py-20">
        
        {/* Header */}
        <header className="mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/20 bg-primary/5 text-primary font-mono text-[10px] uppercase tracking-widest">
            <AlertTriangle className="w-3 h-3" />
            Terms & Conditions
          </div>
          <h1 className="text-5xl font-black text-white tracking-tight">
            Terms of <span className="text-primary">Service</span>
          </h1>
          <p className="font-mono text-xs uppercase tracking-tight text-zinc-500">
            Last Updated: {lastUpdated}
          </p>
        </header>

        <Separator className="bg-zinc-800 mb-16" />

        {/* Intro */}
        <div className="space-y-12">
          <section className="bg-zinc-950 border border-zinc-800 p-8 rounded-2xl">
            <p className="text-sm leading-relaxed text-zinc-300">
              These Terms of Service govern your use of our platform and services. 
              By using the platform, you acknowledge that you understand how the service works, 
              including any usage-based limitations such as credits or tokens.
            </p>
          </section>

          {/* Core Terms */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {legalSections.map((section) => (
              <div
                key={section.title}
                className="p-6 border border-zinc-900 rounded-xl hover:border-zinc-800 transition-colors"
              >
                <div className="flex items-center gap-3 mb-4">
                  {section.icon}
                  <h2 className="text-white font-mono font-bold uppercase text-sm tracking-tight">
                    {section.title}
                  </h2>
                </div>
                <p className="text-xs leading-relaxed text-zinc-500">
                  {section.content}
                </p>
              </div>
            ))}
          </div>

          <Separator className="bg-zinc-800" />

          {/* Additional Clauses */}
          <div className="space-y-8">
            <article className="space-y-4">
              <h3 className="text-white text-lg font-bold">
                5. Limitation of Liability
              </h3>
              <p className="text-sm leading-relaxed border-l-2 border-primary/20 pl-6">
                To the fullest extent permitted by law, we are not liable for any indirect, 
                incidental, or consequential damages arising from your use of the platform. 
                This includes, but is not limited to, reliance on AI-generated outputs.
              </p>
            </article>

            <article className="space-y-4">
              <h3 className="text-white text-lg font-bold">
                6. Subscriptions and Refunds
              </h3>
              <p className="text-sm leading-relaxed border-l-2 border-primary/20 pl-6">
                Subscription plans provide recurring access to tokens or features. 
                Unused tokens may expire depending on your plan. Refunds are considered 
                on a case-by-case basis and are generally not available after usage has begun.
              </p>
            </article>
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-24 pt-12 border-t border-zinc-900 flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-[10px] font-mono text-zinc-600 uppercase tracking-widest">
            © {new Date().getFullYear()} 3CAI. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  );
}